/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package steam;

/**
 *
 * @author edgva
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addplayer = new javax.swing.JButton();
        AgregarJuego = new javax.swing.JButton();
        Descargar = new javax.swing.JButton();
        Reportes = new javax.swing.JButton();
        Juegos = new javax.swing.JButton();
        Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addplayer.setText("Agregar Jugador");
        addplayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addplayerActionPerformed(evt);
            }
        });

        AgregarJuego.setText("Agregar Juego");
        AgregarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarJuegoActionPerformed(evt);
            }
        });

        Descargar.setText("Descargar");
        Descargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescargarActionPerformed(evt);
            }
        });

        Reportes.setText("Reportes");
        Reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportesActionPerformed(evt);
            }
        });

        Juegos.setText("Ver Juegos");
        Juegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JuegosActionPerformed(evt);
            }
        });

        Salir.setText("Cerrar Sesion");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Salir)
                    .addComponent(Juegos)
                    .addComponent(Reportes)
                    .addComponent(Descargar)
                    .addComponent(AgregarJuego)
                    .addComponent(addplayer))
                .addContainerGap(262, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(addplayer)
                .addGap(18, 18, 18)
                .addComponent(AgregarJuego)
                .addGap(18, 18, 18)
                .addComponent(Descargar)
                .addGap(18, 18, 18)
                .addComponent(Reportes)
                .addGap(18, 18, 18)
                .addComponent(Juegos)
                .addGap(18, 18, 18)
                .addComponent(Salir)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addplayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addplayerActionPerformed
        // TODO add your handling code here:
        AgregarJugador jn=new AgregarJugador();
        jn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addplayerActionPerformed

    private void AgregarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarJuegoActionPerformed
        // TODO add your handling code here:
        AgregarJuego la=new AgregarJuego();
        la.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_AgregarJuegoActionPerformed

    private void DescargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescargarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescargarActionPerformed

    private void ReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportesActionPerformed
        // TODO add your handling code here:
        Reportes l=new Reportes();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ReportesActionPerformed

    private void JuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JuegosActionPerformed
        // TODO add your handling code here:
        VerJuego l=new VerJuego();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JuegosActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        
        Login_Admin ll=new Login_Admin();
        ll.setVisible(true);
        this.dispose();
        //System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarJuego;
    private javax.swing.JButton Descargar;
    private javax.swing.JButton Juegos;
    private javax.swing.JButton Reportes;
    private javax.swing.JButton Salir;
    private javax.swing.JButton addplayer;
    // End of variables declaration//GEN-END:variables
}
